// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 시드 스크립트 설정: `npx prisma db seed` 실행 시 사용
    seed: `npx ts-node ${path.join("prisma", "seed.ts")}`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
